# Build configuration for Home Assistant addon
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-advanced-options

build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19

args:
  BUILD_ARCH: ${BUILD_ARCH}
  BUILD_DATE: ${BUILD_DATE}
  BUILD_DESCRIPTION: "AI skill ecosystem for Home Assistant"
  BUILD_NAME: "TrikHub Server"
  BUILD_REF: ${BUILD_REF}
  BUILD_REPOSITORY: "trikhub/trikhub-ha-addons"
  BUILD_VERSION: ${BUILD_VERSION}

labels:
  org.opencontainers.image.title: "TrikHub Server"
  org.opencontainers.image.description: "AI skill ecosystem for Home Assistant"
  org.opencontainers.image.vendor: "TrikHub"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.source: "https://github.com/trikhub/trikhub-ha-addons"
  io.hass.type: "addon"
